language: python

os: linux

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - echo "CPU count == `nproc`"
  - docker --version
  - docker build -t pykaldi .
  - docker tag pykaldi $DOCKER_USERNAME/pykaldi
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/pykaldi:latest
