sudo: required

language: python

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker --version
  - docker build -t pykaldi .
  - docker tag py-poppler $DOCKER_USERNAME/pykaldi
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/pykaldi:latest
