language: python

os: linux

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cd min
  - docker build -t $DOCKER_USERNAME/pykaldi:min .
  - docker push $DOCKER_USERNAME/pykaldi:min
  - cd ../latest
  - docker build -t $DOCKER_USERNAME/pykaldi:latest .
  - docker push $DOCKER_USERNAME/pykaldi:latest
